### ISSUE TITLE
package causes jest tests to fail

### ISSUE THREAD

**Issue by Benchelbikh-Mohammed** [ej-shafran/react-sound-visualizer#4]
Hi there !

i am a developer in project using this package. it is a react ts project that uses jest for unit testing.
Jest tests are failing, here's the log errors

```

Jest encountered an unexpected token
Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.


Details:

<root-dir>/node_modules/react-sound-visualizer/index.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){export * from './useVisualizer';
                                                                                  ^^^^^^

SyntaxError: Unexpected token 'export'

      12 | import { DiagnosticAccordion } from '../../components/DiagnosticAccordion/DiagnosticAccordion';
      13 | import { MicButton } from '../../components/MicButton/MicButton';
    > 14 | import { Visualizer } from "react-sound-visualizer";
         | ^
      15 | import { usePermission } from 'use-permission';
      16 | import { MicrophoneDiagnosticMessage, MicrophoneNextStep, QueryPermissionError } from '../../../service/speech/MicrophoneDiagnosticService';
      17 | import { LocalStorageRepository } from '../../../repository/LocalStorageRepository';

      at Runtime.createScriptFromCode (node_modules/react-scripts/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (src/core/ui/screens/diagnostic/MicrophoneDiagnosticScreen.tsx:14:1)

```

I don't know for sure if the problem is with the package itself or it can be fixed with the right jest configuration, one thing i am sure of is no other package is causing this issue and its been persistent, throughout different versions of our jest config.

craco jest config : 
```

  jest: {
    configure(config : any) {
      config.globals = {
        'ts-jest': {
          useESM: true,
        },
      };
      config.preset = 'ts-jest';
      config.transformIgnorePatterns = ['<rootDir>/node_modules/react-sound-visualizer'];
      config.transform = {
        '^.+\\.js$': ['babel-jest', { rootMode: 'upward' }],
        "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js",
        "^.+\\.svg$": "<rootDir>/svgTransform.js",
        ".+\\.(css|styl|less|sass|scss)$": "<rootDir>/node_modules/jest-css-modules-transform",
      };
      return config;
    },
  },

```
I found on different sources that transformIgnorePatterns should prevent jest from trying to parse package files, it's not working. 

Index.js is trying to export hooks this way : export * from './useVisualizer'; which seems to be reason why jest fails to parse it.

Your help would be much appreciated, thank you !

Mohammed

**Comment by ej-shafran** [comment]
Hi - sorry for the late response, been really busy recently.

I'll give it a look sometime this week - this seems to be related to `esm` and `cjs` stuff...

**Comment by Benchelbikh-Mohammed** [comment]
Thank you for the time and effort you put into this. I'll be eagerly waiting for your response.

**Comment by Benchelbikh-Mohammed** [comment]
Hi, have you had the opportunity to look into it ? We need to make Jest running by the end of the month.

**Comment by ej-shafran** [comment]
A fix should be available with `npm install react-sound-visualizer@1.1.0`
